# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mesh_surface.ui'
#
# Created: Wed Jul 24 23:18:11 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MeshSurface(object):
    def setupUi(self, MeshSurface):
        MeshSurface.setObjectName(_fromUtf8("MeshSurface"))
        MeshSurface.resize(550, 787)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/mesh_surface/icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MeshSurface.setWindowIcon(icon)
        self.buttonBox = QtGui.QDialogButtonBox(MeshSurface)
        self.buttonBox.setGeometry(QtCore.QRect(350, 750, 191, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.frame = QtGui.QFrame(MeshSurface)
        self.frame.setGeometry(QtCore.QRect(10, 330, 531, 201))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.grpNCDF = QtGui.QGroupBox(self.frame)
        self.grpNCDF.setEnabled(True)
        self.grpNCDF.setGeometry(QtCore.QRect(10, 10, 521, 191))
        self.grpNCDF.setToolTip(_fromUtf8(""))
        self.grpNCDF.setWhatsThis(_fromUtf8(""))
        self.grpNCDF.setAutoFillBackground(False)
        self.grpNCDF.setFlat(False)
        self.grpNCDF.setCheckable(True)
        self.grpNCDF.setChecked(True)
        self.grpNCDF.setObjectName(_fromUtf8("grpNCDF"))
        self.singleNetCDFGroupBox = QtGui.QGroupBox(self.grpNCDF)
        self.singleNetCDFGroupBox.setEnabled(True)
        self.singleNetCDFGroupBox.setGeometry(QtCore.QRect(30, 50, 481, 81))
        self.singleNetCDFGroupBox.setTitle(_fromUtf8(""))
        self.singleNetCDFGroupBox.setObjectName(_fromUtf8("singleNetCDFGroupBox"))
        self.singleNetCDFChooseFilesPushButton = QtGui.QPushButton(self.singleNetCDFGroupBox)
        self.singleNetCDFChooseFilesPushButton.setEnabled(False)
        self.singleNetCDFChooseFilesPushButton.setGeometry(QtCore.QRect(390, 40, 85, 27))
        self.singleNetCDFChooseFilesPushButton.setObjectName(_fromUtf8("singleNetCDFChooseFilesPushButton"))
        self.singleNetCDFChooseFilesLineEdit = QtGui.QLineEdit(self.singleNetCDFGroupBox)
        self.singleNetCDFChooseFilesLineEdit.setEnabled(False)
        self.singleNetCDFChooseFilesLineEdit.setGeometry(QtCore.QRect(180, 40, 201, 27))
        self.singleNetCDFChooseFilesLineEdit.setObjectName(_fromUtf8("singleNetCDFChooseFilesLineEdit"))
        self.singleNetCDFLayersRadioButton = QtGui.QRadioButton(self.singleNetCDFGroupBox)
        self.singleNetCDFLayersRadioButton.setGeometry(QtCore.QRect(0, 10, 160, 22))
        self.singleNetCDFLayersRadioButton.setObjectName(_fromUtf8("singleNetCDFLayersRadioButton"))
        self.singleNetCDFLayerDropDown = QtGui.QComboBox(self.singleNetCDFGroupBox)
        self.singleNetCDFLayerDropDown.setEnabled(False)
        self.singleNetCDFLayerDropDown.setGeometry(QtCore.QRect(180, 10, 201, 27))
        self.singleNetCDFLayerDropDown.setObjectName(_fromUtf8("singleNetCDFLayerDropDown"))
        self.singleNetCDFChooseFilesRadioButton = QtGui.QRadioButton(self.singleNetCDFGroupBox)
        self.singleNetCDFChooseFilesRadioButton.setGeometry(QtCore.QRect(0, 40, 114, 22))
        self.singleNetCDFChooseFilesRadioButton.setObjectName(_fromUtf8("singleNetCDFChooseFilesRadioButton"))
        self.singleNetCDFRadioButton = QtGui.QRadioButton(self.grpNCDF)
        self.singleNetCDFRadioButton.setGeometry(QtCore.QRect(10, 30, 183, 22))
        self.singleNetCDFRadioButton.setChecked(True)
        self.singleNetCDFRadioButton.setObjectName(_fromUtf8("singleNetCDFRadioButton"))
        self.addLayerToCanvasCheckBox = QtGui.QCheckBox(self.grpNCDF)
        self.addLayerToCanvasCheckBox.setEnabled(False)
        self.addLayerToCanvasCheckBox.setGeometry(QtCore.QRect(30, 160, 126, 22))
        self.addLayerToCanvasCheckBox.setObjectName(_fromUtf8("addLayerToCanvasCheckBox"))
        self.multipleNetCDFFilesRadioButton = QtGui.QRadioButton(self.grpNCDF)
        self.multipleNetCDFFilesRadioButton.setGeometry(QtCore.QRect(11, 130, 370, 22))
        self.multipleNetCDFFilesRadioButton.setChecked(False)
        self.multipleNetCDFFilesRadioButton.setObjectName(_fromUtf8("multipleNetCDFFilesRadioButton"))
        self.frame_2 = QtGui.QFrame(MeshSurface)
        self.frame_2.setGeometry(QtCore.QRect(10, 10, 531, 311))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.grpDom = QtGui.QGroupBox(self.frame_2)
        self.grpDom.setGeometry(QtCore.QRect(10, 10, 521, 271))
        self.grpDom.setFlat(False)
        self.grpDom.setObjectName(_fromUtf8("grpDom"))
        self.domainShapefileLayerDropDown = QtGui.QComboBox(self.grpDom)
        self.domainShapefileLayerDropDown.setGeometry(QtCore.QRect(210, 30, 201, 27))
        self.domainShapefileLayerDropDown.setObjectName(_fromUtf8("domainShapefileLayerDropDown"))
        self.domainShapefileLayerRadioButton = QtGui.QRadioButton(self.grpDom)
        self.domainShapefileLayerRadioButton.setGeometry(QtCore.QRect(10, 30, 190, 22))
        self.domainShapefileLayerRadioButton.setChecked(True)
        self.domainShapefileLayerRadioButton.setObjectName(_fromUtf8("domainShapefileLayerRadioButton"))
        self.grpDefID = QtGui.QGroupBox(self.grpDom)
        self.grpDefID.setEnabled(True)
        self.grpDefID.setGeometry(QtCore.QRect(30, 90, 391, 91))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.grpDefID.setFont(font)
        self.grpDefID.setAcceptDrops(False)
        self.grpDefID.setCheckable(True)
        self.grpDefID.setChecked(False)
        self.grpDefID.setObjectName(_fromUtf8("grpDefID"))
        self.label_2 = QtGui.QLabel(self.grpDefID)
        self.label_2.setGeometry(QtCore.QRect(30, 30, 67, 17))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.IdDropdown = QtGui.QComboBox(self.grpDefID)
        self.IdDropdown.setGeometry(QtCore.QRect(180, 30, 201, 27))
        self.IdDropdown.setObjectName(_fromUtf8("IdDropdown"))
        self.label_3 = QtGui.QLabel(self.grpDefID)
        self.label_3.setGeometry(QtCore.QRect(30, 60, 71, 17))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.Default_Id = QtGui.QLineEdit(self.grpDefID)
        self.Default_Id.setGeometry(QtCore.QRect(180, 60, 201, 27))
        self.Default_Id.setObjectName(_fromUtf8("Default_Id"))
        self.Threshold = QtGui.QLineEdit(self.grpDom)
        self.Threshold.setEnabled(True)
        self.Threshold.setGeometry(QtCore.QRect(210, 60, 201, 27))
        self.Threshold.setObjectName(_fromUtf8("Threshold"))
        self.define_th = QtGui.QCheckBox(self.grpDom)
        self.define_th.setEnabled(True)
        self.define_th.setGeometry(QtCore.QRect(30, 60, 141, 22))
        self.define_th.setObjectName(_fromUtf8("define_th"))
        self.lineGroupBox = QtGui.QGroupBox(self.grpDom)
        self.lineGroupBox.setGeometry(QtCore.QRect(20, 210, 391, 31))
        self.lineGroupBox.setTitle(_fromUtf8(""))
        self.lineGroupBox.setObjectName(_fromUtf8("lineGroupBox"))
        self.lineRadioButton = QtGui.QRadioButton(self.lineGroupBox)
        self.lineRadioButton.setGeometry(QtCore.QRect(190, 10, 71, 22))
        self.lineRadioButton.setChecked(True)
        self.lineRadioButton.setObjectName(_fromUtf8("lineRadioButton"))
        self.bSplineRadioButton = QtGui.QRadioButton(self.lineGroupBox)
        self.bSplineRadioButton.setGeometry(QtCore.QRect(280, 10, 91, 22))
        self.bSplineRadioButton.setObjectName(_fromUtf8("bSplineRadioButton"))
        self.label_5 = QtGui.QLabel(self.lineGroupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 67, 17))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.compoundCheckBox = QtGui.QCheckBox(self.grpDom)
        self.compoundCheckBox.setGeometry(QtCore.QRect(30, 190, 171, 22))
        self.compoundCheckBox.setChecked(True)
        self.compoundCheckBox.setObjectName(_fromUtf8("compoundCheckBox"))
        self.grpChooseGeo = QtGui.QGroupBox(self.frame_2)
        self.grpChooseGeo.setEnabled(True)
        self.grpChooseGeo.setGeometry(QtCore.QRect(10, 270, 501, 41))
        self.grpChooseGeo.setTitle(_fromUtf8(""))
        self.grpChooseGeo.setObjectName(_fromUtf8("grpChooseGeo"))
        self.chooseGeoFileRadioButton = QtGui.QRadioButton(self.grpChooseGeo)
        self.chooseGeoFileRadioButton.setGeometry(QtCore.QRect(10, 0, 177, 22))
        self.chooseGeoFileRadioButton.setChecked(False)
        self.chooseGeoFileRadioButton.setObjectName(_fromUtf8("chooseGeoFileRadioButton"))
        self.chooseGeoFileLineEdit = QtGui.QLineEdit(self.grpChooseGeo)
        self.chooseGeoFileLineEdit.setEnabled(True)
        self.chooseGeoFileLineEdit.setGeometry(QtCore.QRect(200, 0, 201, 27))
        self.chooseGeoFileLineEdit.setObjectName(_fromUtf8("chooseGeoFileLineEdit"))
        self.chooseGeoFilePushButton = QtGui.QPushButton(self.grpChooseGeo)
        self.chooseGeoFilePushButton.setEnabled(True)
        self.chooseGeoFilePushButton.setGeometry(QtCore.QRect(410, 0, 85, 27))
        self.chooseGeoFilePushButton.setObjectName(_fromUtf8("chooseGeoFilePushButton"))
        self.frame_5 = QtGui.QFrame(MeshSurface)
        self.frame_5.setGeometry(QtCore.QRect(10, 540, 531, 201))
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.grpCSpace_2 = QtGui.QGroupBox(self.frame_5)
        self.grpCSpace_2.setGeometry(QtCore.QRect(10, 10, 511, 181))
        self.grpCSpace_2.setCheckable(True)
        self.grpCSpace_2.setObjectName(_fromUtf8("grpCSpace_2"))
        self.sphereRadioButton = QtGui.QRadioButton(self.grpCSpace_2)
        self.sphereRadioButton.setGeometry(QtCore.QRect(250, 30, 131, 22))
        self.sphereRadioButton.setObjectName(_fromUtf8("sphereRadioButton"))
        self.meshingAlgorithmDropDown = QtGui.QComboBox(self.grpCSpace_2)
        self.meshingAlgorithmDropDown.setGeometry(QtCore.QRect(210, 60, 201, 27))
        self.meshingAlgorithmDropDown.setObjectName(_fromUtf8("meshingAlgorithmDropDown"))
        self.flatRadioButton = QtGui.QRadioButton(self.grpCSpace_2)
        self.flatRadioButton.setGeometry(QtCore.QRect(170, 30, 74, 22))
        self.flatRadioButton.setAcceptDrops(False)
        self.flatRadioButton.setChecked(True)
        self.flatRadioButton.setObjectName(_fromUtf8("flatRadioButton"))
        self.label = QtGui.QLabel(self.grpCSpace_2)
        self.label.setGeometry(QtCore.QRect(40, 30, 120, 17))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_4 = QtGui.QLabel(self.grpCSpace_2)
        self.label_4.setGeometry(QtCore.QRect(40, 60, 69, 17))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.commandLineGroupBox = QtGui.QGroupBox(self.grpCSpace_2)
        self.commandLineGroupBox.setGeometry(QtCore.QRect(30, 80, 441, 101))
        self.commandLineGroupBox.setTitle(_fromUtf8(""))
        self.commandLineGroupBox.setCheckable(False)
        self.commandLineGroupBox.setObjectName(_fromUtf8("commandLineGroupBox"))
        self.commandEdit = QtGui.QToolButton(self.commandLineGroupBox)
        self.commandEdit.setGeometry(QtCore.QRect(390, 20, 24, 25))
        self.commandEdit.setCheckable(True)
        self.commandEdit.setObjectName(_fromUtf8("commandEdit"))
        self.commandTextEdit = QtGui.QTextEdit(self.commandLineGroupBox)
        self.commandTextEdit.setGeometry(QtCore.QRect(10, 20, 371, 78))
        self.commandTextEdit.setObjectName(_fromUtf8("commandTextEdit"))
        self.steriographicRadioButton = QtGui.QRadioButton(self.grpCSpace_2)
        self.steriographicRadioButton.setGeometry(QtCore.QRect(390, 30, 117, 22))
        self.steriographicRadioButton.setObjectName(_fromUtf8("steriographicRadioButton"))

        self.retranslateUi(MeshSurface)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), MeshSurface.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), MeshSurface.reject)
        QtCore.QObject.connect(self.singleNetCDFChooseFilesRadioButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.singleNetCDFChooseFilesLineEdit.setEnabled)
        QtCore.QObject.connect(self.singleNetCDFLayersRadioButton, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.singleNetCDFLayerDropDown.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MeshSurface)

    def retranslateUi(self, MeshSurface):
        MeshSurface.setWindowTitle(_translate("MeshSurface", "Mesh Polygon", None))
        self.grpNCDF.setTitle(_translate("MeshSurface", "Use NetCDF Mesh Metric", None))
        self.singleNetCDFChooseFilesPushButton.setText(_translate("MeshSurface", "Browse", None))
        self.singleNetCDFLayersRadioButton.setText(_translate("MeshSurface", "Choose From Layer", None))
        self.singleNetCDFChooseFilesRadioButton.setText(_translate("MeshSurface", "Choose File", None))
        self.singleNetCDFRadioButton.setText(_translate("MeshSurface", "Use Single NetCDF File", None))
        self.addLayerToCanvasCheckBox.setText(_translate("MeshSurface", "Add to Canvas", None))
        self.multipleNetCDFFilesRadioButton.setText(_translate("MeshSurface", "Calculate Minumum Value of Visible NetCDF Files", None))
        self.grpDom.setTitle(_translate("MeshSurface", "Domain", None))
        self.domainShapefileLayerRadioButton.setText(_translate("MeshSurface", "Domain Shapefile Layer", None))
        self.grpDefID.setTitle(_translate("MeshSurface", "Define Boundary ID ", None))
        self.label_2.setText(_translate("MeshSurface", "ID Layer", None))
        self.label_3.setText(_translate("MeshSurface", "Default ID", None))
        self.define_th.setText(_translate("MeshSurface", "Define Threshold", None))
        self.lineRadioButton.setText(_translate("MeshSurface", "Line", None))
        self.bSplineRadioButton.setText(_translate("MeshSurface", "BSpline", None))
        self.label_5.setText(_translate("MeshSurface", "Line Type", None))
        self.compoundCheckBox.setToolTip(_translate("MeshSurface", "WARNING: Using Compound Lines increses the meshing time#", None))
        self.compoundCheckBox.setText(_translate("MeshSurface", "Use Compound Lines", None))
        self.chooseGeoFileRadioButton.setText(_translate("MeshSurface", "Choose Geo File", None))
        self.chooseGeoFilePushButton.setText(_translate("MeshSurface", "Browse", None))
        self.grpCSpace_2.setTitle(_translate("MeshSurface", "Generate Mesh", None))
        self.sphereRadioButton.setText(_translate("MeshSurface", "Lon-Lat Sphere", None))
        self.flatRadioButton.setText(_translate("MeshSurface", "Planar", None))
        self.label.setText(_translate("MeshSurface", "Projection", None))
        self.label_4.setText(_translate("MeshSurface", "Algorithm", None))
        self.commandEdit.setText(_translate("MeshSurface", "E", None))
        self.steriographicRadioButton.setText(_translate("MeshSurface", "Steriographic", None))

